#! /bin/ksh
NAME=ED
EXES="sp"

. ./common/PARSE.sh

if [ $RAPIDFIRE -eq 0 ]; then
  case $NGBCLASS in 
    S   )   WIDTH=9      ;;
    W   )   WIDTH=9      ;;
    A   )   WIDTH=9      ;;
    B   )   WIDTH=18     ;;
    C   )   WIDTH=36     ;;
  esac
else
  case $NGBCLASS in 
    S   )   WIDTH=9      ;;
    W   )   WIDTH=600    ;;
    A   )   WIDTH=2500   ;;
    B   )   WIDTH=10000  ;;
    C   )   WIDTH=40000  ;;
  esac
fi
    
DEPTH=1
MAX_TASK=`expr $WIDTH \* $DEPTH`

. ./common/DEPLOY.sh

CODE=sp
FILTER=0
NUM_INPUTS=0
VERIFY=1

TASK=0
while [ $TASK -lt $MAX_TASK ]; do
  . ./common/NODE.sh
  TASK=`expr $TASK + 1`
done

. ./common/VERIFY.sh


